### ISSUE TITLE
std::wstring with utf16 serialization bug

### ISSUE THREAD

**Issue by daldegam** [niXman/yas#67]
Hello! 

I have a little bug serializing std::wstring objects.
The bug happens when I put characters like UTF-16.

I changed your wstring test to reproduce the problem:

```
#ifndef __yas__tests__base__include__wstring_hpp
#define __yas__tests__base__include__wstring_hpp

/***************************************************************************/

template<typename archive_traits>
bool wstring_test(std::ostream &log, const char *archive_type, const char *test_name) {

	std::vector<std::wstring> wcs_collection = {
		L"A E I O U c C d D p P Á É Í Ó Ú ç Ç d D p P à è ì ò ù ã õ â ê î ô û", // pt-br
		//L"☺ ☻ ♥ ♦ ♣ ♠ • ◘ ○ ◙ ♂ ♀ ♪ ♫ ☼ ► ◄ ↕ ‼ ¶ § ▬ ↨ ↑ ↓ → ← ∟ ↔ ▲ ▼", // symbols
		L"đái dầm chửa hoang bí mật bầy tôi", // vn
		L"我能吞下玻璃而不伤身体。", // zh-cn
		L"私はガラスを食べられます。それは私を傷つけません。", // ja
		L"मैं काँच खा सकता हूँ, मुझे उस से कोई पीडा नहीं होती.", // hi
		L"Я могу есть стекло, оно мне не вредит.", // ru
		L"나는 유리를 먹을 수 있어요. 그래도 아프지 않아요", // ko
		L"I can eat glass and it doesn't hurt me.", // en
		L"ฉันกินกระจกได้ แต่มันไม่ทำให้ฉันเจ็บ", // th
		L"أنا قادر على أكل الزجاج و هذا لا يؤلمني", // ar
		L"לְהַגִּיד בַּבֹּקֶר חַסְדֶּךָ וֶאֱמוּנָתְךָ בַּלֵּילוֹת", // he
		L"Μπορώ να φάω σπασμένα γυαλιά χωρίς να πάθω τίποτα.", // el
		L"Mohu jíst sklo, neublíží mi.", // cs
		L"Мога да ям стъкло, то не ми вреди.", // bg
		L"Cam yiyebilirim, bana zararı dokunmaz.", // tr
		L"Je peux manger du verre, ça ne me fait pas de mal.", // fr
	};

	for (auto& ws : wcs_collection)
	{
		std::wstring wss;

		typename archive_traits::oarchive oa;
		archive_traits::ocreate(oa, archive_type);
		oa& YAS_OBJECT_NVP("obj", ("ws", ws));

		typename archive_traits::iarchive ia;
		archive_traits::icreate(ia, oa, archive_type);
		ia& YAS_OBJECT_NVP("obj", ("ws", wss));

		if (ws != wss) {
			YAS_TEST_REPORT(log, archive_type, test_name);
			return false;
		}
	}

	return true;
}

/***************************************************************************/

#endif // __yas__tests__base__include__wstring_hpp
```

```/***************************************************/
cmdline: binary

binary: header                   -> passed
binary: endian                   -> passed
binary: version                  -> passed
binary: base64                   -> passed
binary: fundamental              -> passed
binary: compacted_storage_size   -> passed
binary: enum                     -> passed
binary: auto_array               -> passed
binary: std_streams              -> passed
binary: one_function             -> passed
binary: split_functions          -> passed
binary: one_method               -> passed
binary: split_methods            -> passed
binary: serialize                -> passed
binary: serialization            -> passed
binary: yas_object               -> passed
binary: base_object              -> passed
binary: array                    -> passed
binary: bitset                   -> passed
binary: buffer                   -> passed
binary: chrono                   -> passed
binary: complex                  -> passed
binary: string                   -> passed
binary: string_view              -> passed
binary: wstring                  -> [...]yas\tests\base\include\wstring.hpp(77): archive: "binary", test: "wstring" failed!
failed
binary: pair                     -> passed
binary: tuple                    -> passed
binary: vector                   -> passed
binary: list                     -> passed
binary: forward_list             -> passed
binary: deque                    -> passed
binary: map                      -> passed
binary: set                      -> passed
binary: multimap                 -> passed
binary: multiset                 -> passed
binary: unordered_map            -> passed
binary: unordered_set            -> passed
binary: unordered_multimap       -> passed
binary: unordered_multiset       -> passed
binary: optional                 -> passed
binary: variant                  -> passed
binary: boost_fusion_pair        -> passed
binary: boost_fusion_tuple       -> passed
binary: boost_fusion_vector      -> passed
binary: boost_fusion_list        -> passed
binary: boost_fusion_set         -> passed
binary: boost_fusion_map         -> passed
binary: boost_cont_string        -> passed
binary: boost_cont_wstring       -> passed
binary: boost_cont_vector        -> passed
binary: boost_cont_static_vector -> passed
binary: boost_cont_stable_vector -> passed
binary: boost_cont_list          -> passed
binary: boost_cont_slist         -> passed
binary: boost_cont_map           -> passed
binary: boost_cont_multimap      -> passed
binary: boost_cont_set           -> passed
binary: boost_cont_multiset      -> passed
binary: boost_cont_flat_map      -> passed
binary: boost_cont_flat_multimap -> passed
binary: boost_cont_flat_set      -> passed
binary: boost_cont_flat_multiset -> passed
binary: boost_cont_deque         -> passed
binary: boost_tuple              -> passed
binary: boost_variant            -> passed

/***************************************************/
> passed tests: 64
> failed tests: 1
> host endian : little
> host bits   : 64
> YAS version : 7.0.4
/***************************************************/
```

Test performed with Visual Studio 2019 - ISO C++14 Standard (/std:c++14)

Thanks :)

**Comment by niXman** [comment]
Hi,

very strange... I think something like that I have fixed...

will check.
thanks

**Comment by niXman** [comment]
> Test performed with Visual Studio 2019 - ISO C++14 Standard (/std:c++14)

did you check this using another compiler? or just MSVC?

**Comment by daldegam** [comment]
I used just MSVC for this test.
Now I repeated the test with ISO C++17 Standard (/std:c++17) and bug persist.

**Comment by niXman** [comment]
just now I have tested using your testdata with gcc-7.4 & gcc-8.3 and this test was successful...

will think. I have no access for windows for now...

**Comment by daldegam** [comment]
Well, I'm trying to debug to see if I can find anything relevant.
It seems that there is a problem when it tries to convert the data into function: `template<typename D, typename S> void to_utf8(D &dst, const S &src)`

I am sending some prints before and after passing through function.

Before:
<img width="1296" alt="print1" src="https://user-images.githubusercontent.com/228961/65164739-dd16bf00-da13-11e9-980f-4dabc12c43af.png">

After:
<img width="1299" alt="print2" src="https://user-images.githubusercontent.com/228961/65164740-dd16bf00-da13-11e9-8f2c-8f8229811db5.png">

Inside function, see this detail:
<img width="1302" alt="print3" src="https://user-images.githubusercontent.com/228961/65165013-56161680-da14-11e9-9942-33e2872b3bb7.png">

Character: `ầ == 7847 == 0x1EA7`

But this preprocessor `WCHAR_MAX` it's disabled... so this character it's ignored.

**Comment by daldegam** [comment]
I commented to the preprocessor and the test passed.

See the print below:
<img width="1207" alt="print4" src="https://user-images.githubusercontent.com/228961/65165754-c5403a80-da15-11e9-9386-ca9e86c3fada.png">

**Comment by niXman** [comment]
is `std::wstring::value_type` the same as `wchar_t`?
is `sizeof(std::wstring::value_type) == 2`? or 4?

**Comment by niXman** [comment]
> I commented to the preprocessor and the test passed.

great, but I need to understand how to fix it correctly...

**Comment by daldegam** [comment]
> is `std::wstring::value_type` the same as `wchar_t`?
> is `sizeof(std::wstring::value_type) == 2`? or 4?

```
sizeof(char): 1
sizeof(wchar_t): 2
sizeof(std::string::value_type): 1
sizeof(std::wstring::value_type): 2
```

**Comment by niXman** [comment]
ok, thank you!

**Comment by niXman** [comment]
@daldegam can you please provide me the value of the `WCHAR_MAX` macro?

**Comment by daldegam** [comment]
> @daldegam can you please provide me the value of the `WCHAR_MAX` macro?

`#define WCHAR_MAX 0xffff`

**Comment by daldegam** [comment]
Wouldn't the fix simply pass ifdef to if below?

Why does it appear that it is in the wrong place.

Check it out:
```
template<typename D, typename S>
void to_utf8(D &dst, const S &src) {
	for ( auto it = src.begin(); it != src.end(); ++it ) {
		std::wstring::value_type nchar = *it;
		if (nchar <= 0x7F) {
			dst += __YAS_SCAST(std::string::value_type, nchar);
		} else if (nchar <= 0x07FF) {
			dst += __YAS_SCAST(char, 0xC0 | (nchar >> 6));
			dst += __YAS_SCAST(char, 0x80 | (nchar & 0x3F));
		} else if (nchar <= 0xFFFF) {
			dst += __YAS_SCAST(char, 0xE0 | (nchar >> 12));
			dst += __YAS_SCAST(char, 0x80 | ((nchar >> 6) & 0x3F));
			dst += __YAS_SCAST(char, 0x80 | (nchar & 0x3F));
		}
#if WCHAR_MAX > 0xFFFF
		else if (nchar <= 0x1FFFFF) {
			dst += __YAS_SCAST(char, 0xF0 | (nchar >> 18));
			dst += __YAS_SCAST(char, 0x80 | ((nchar >> 12) & 0x3F));
			dst += __YAS_SCAST(char, 0x80 | ((nchar >> 6) & 0x3F));
			dst += __YAS_SCAST(char, 0x80 | (nchar & 0x3F));
		}
#endif
	}
}
```

Ifdef is correct in the fourth condition, because if it is less than 0xFFFF it must still enter the third condition `if (nchar <= 0xFFFF)`.

**Comment by niXman** [comment]
yes, I think you're right

**Comment by niXman** [comment]
thank you!
closed.
